// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnn1CVwJupmdvAul6oA2XVLK5PjkGhVvg',
    appId: '1:259666937018:web:c6a8d3adea896f022a2e83',
    messagingSenderId: '259666937018',
    projectId: 'linkyou-79017',
    authDomain: 'linkyou-79017.firebaseapp.com',
    storageBucket: 'linkyou-79017.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEDPj97kFNkxsOFTs-emrTLu8T4zVxKew',
    appId: '1:259666937018:android:38e9d24a15eee2942a2e83',
    messagingSenderId: '259666937018',
    projectId: 'linkyou-79017',
    storageBucket: 'linkyou-79017.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWSQmH3CeH0L2hz8zmkSpybSLc_8zPMsE',
    appId: '1:259666937018:ios:7d35c3fd9c4ce2532a2e83',
    messagingSenderId: '259666937018',
    projectId: 'linkyou-79017',
    storageBucket: 'linkyou-79017.appspot.com',
    iosBundleId: 'com.example.linkyouTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWSQmH3CeH0L2hz8zmkSpybSLc_8zPMsE',
    appId: '1:259666937018:ios:7d35c3fd9c4ce2532a2e83',
    messagingSenderId: '259666937018',
    projectId: 'linkyou-79017',
    storageBucket: 'linkyou-79017.appspot.com',
    iosBundleId: 'com.example.linkyouTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnn1CVwJupmdvAul6oA2XVLK5PjkGhVvg',
    appId: '1:259666937018:web:fec9318c9c41ad552a2e83',
    messagingSenderId: '259666937018',
    projectId: 'linkyou-79017',
    authDomain: 'linkyou-79017.firebaseapp.com',
    storageBucket: 'linkyou-79017.appspot.com',
  );
}
